stages:
  - build
  - push

before_script:
  - make init

.action: &action
  script:
    - git branch -v
    - env | sort
    - make $CI_JOB_NAME
  tags:
    - ubuntu-16.04
    - kote6

.build_action: &build_action
  stage: build
  <<: *action
  variables:
    NO_CACHE: "--no-cache"

.push_action: &push_action
  stage: push
  when: manual
  <<: *action

build_MNPR:
  <<: *build_action

push_MNPR:
  <<: *push_action
  except:
    - tags

push_MNP:
  <<: *push_action
  only:
    - tags

push_latest:
  <<: *push_action
  only:
    - tags
